download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-aws-8.1.0.tar.gz
format_version: 1.0.0
name: aws
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 8.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/aws/versions/8.1.0/
