---
- name: Cleanup All Project01 Resources
  hosts: localhost
  connection: local
  vars_files:
    - ./global_vars/all_vars

  tasks:
    ####################################################################
    # 0. VPC ID 조회
    ####################################################################
    - name: Get VPC Info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters: { "tag:Name": "{{ prefix }}-vpc" }
      register: vpc_info

    - name: Set VPC ID Fact
      set_fact:
        target_vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      when: vpc_info.vpcs | length > 0

    ####################################################################
    # 1. 고수준 컴퓨트 / 로드밸런싱 리소스 삭제
    ####################################################################
    - name: Remove Auto Scaling Group
      amazon.aws.autoscaling_group:
        name: "{{ prefix }}-was-asg"
        region: "{{ region }}"
        state: absent
        wait_for_instances: yes
      ignore_errors: yes

    - name: Remove Launch Template
      amazon.aws.ec2_launch_template:
        name: "{{ prefix }}-template"
        region: "{{ region }}"
        state: absent
      ignore_errors: yes

    - name: Remove Application Load Balancer
      amazon.aws.elb_application_lb:
        name: "{{ prefix }}-alb"
        region: "{{ region }}"
        state: absent
        wait: yes
      ignore_errors: yes

    - name: Remove Target Groups
      community.aws.elb_target_group:
        name: "{{ item }}"
        region: "{{ region }}"
        state: absent
      loop:
        - "{{ prefix }}-was-tg"
        - "{{ prefix }}-jenkins-tg"
      ignore_errors: yes

    ####################################################################
    # 2. 단독 EC2 인스턴스 종료 (Jenkins)
    ####################################################################
    - name: Terminate Jenkins Instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        filters: { "tag:Name": "{{ prefix }}-jenkins" }
        state: absent
        wait: yes
      ignore_errors: yes

    ####################################################################
    # 3. NAT Gateway 및 EIP 삭제
    ####################################################################
    - name: Get NAT Gateway Info
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ target_vpc_id }}"
          state: ['available', 'pending', 'deleting']
      register: nat_info
      when: target_vpc_id is defined

    - name: Remove NAT Gateways and WAIT
      amazon.aws.ec2_vpc_nat_gateway:
        region: "{{ region }}"
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        state: absent
        wait: yes
      loop: "{{ nat_info.nat_gateways | default([]) }}"
      when: target_vpc_id is defined and (nat_info.nat_gateways | length > 0)
      ignore_errors: yes

    - name: Release NAT EIP
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        tag_name: "Name"
        tag_value: "{{ prefix }}-nat-eip"
        state: absent
      ignore_errors: yes

    ####################################################################
    # 4. Internet Gateway 분리 및 삭제
    ####################################################################
    - name: Remove Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ target_vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: target_vpc_id is defined
      ignore_errors: yes

    ####################################################################
    # 5. Route Table 삭제
    ####################################################################
    - name: Get Route Tables
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ target_vpc_id }}"
      register: rt_info
      when: target_vpc_id is defined

    - name: Remove Route Tables
      amazon.aws.ec2_vpc_route_table:
        region: "{{ region }}"
        route_table_id: "{{ item.route_table_id }}"
        state: absent
      loop: "{{ rt_info.route_tables | default([]) }}"
      when: target_vpc_id is defined and (rt_info.route_tables | length > 0)
      ignore_errors: yes

    ####################################################################
    # 6. Security Group 삭제
    ####################################################################
    - name: Get Security Groups
      amazon.aws.ec2_security_group_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ target_vpc_id }}"
      register: sg_info
      when: target_vpc_id is defined

    - name: Remove Security Groups (except default)
      amazon.aws.ec2_security_group:
        region: "{{ region }}"
        group_id: "{{ item.group_id }}"
        state: absent
      loop: "{{ sg_info.security_groups | rejectattr('group_name','equalto','default') | list }}"
      when: target_vpc_id is defined and (sg_info.security_groups | length > 0)
      ignore_errors: yes

    ####################################################################
    # 7. Subnet 삭제
    ####################################################################
    - name: Get Remaining Subnets
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters: { "vpc-id": "{{ target_vpc_id }}" }
      register: current_subnets
      when: target_vpc_id is defined

    - name: Remove Subnets
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        vpc_id: "{{ target_vpc_id }}"
        cidr: "{{ item.cidr_block }}"
        state: absent
      loop: "{{ current_subnets.subnets | default([]) }}"
      when: target_vpc_id is defined and (current_subnets.subnets | length > 0)
      ignore_errors: yes

    ####################################################################
    # 8. VPC 최종 삭제
    ####################################################################
    - name: Remove VPC (Final Step)
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ target_vpc_id }}"
        region: "{{ region }}"
        state: absent
      when: target_vpc_id is defined
      ignore_errors: yes

    ####################################################################
    # 9. IAM 리소스 삭제
    ####################################################################
    - name: Remove Instance Profile
      amazon.aws.iam_instance_profile:
        name: "{{ prefix }}-ec2-profile"
        state: absent
      ignore_errors: yes

    - name: Remove EC2 Role
      community.aws.iam_role:
        n
